version: '3.4'
openapi:
components:
info:
openapi:
paths:
info:
webhooks:
openapi:
info:
services:
  weaviate_application:
    image: weaviate/test-server
    build:
      context: .
      dockerfile: Dockerfile
      target: weaviate
    restart: on-failure:0
    ports:
      - "6060:6060"
      - "8080:8080"
      - "2112:2112"
      - "50051:50051"
      - "7101:7101"
    environment:
      LOG_LEVEL: "debug"
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-contextionary
      ENABLE_MODULES: text2vec-contextionary
      PROMETHEUS_MONITORING_ENABLED: 'true'
      PROMETHEUS_MONITORING_GROUP_CLASSES: 'true'
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      ASYNC_INDEXING: ${ASYNC_INDEXING:-false}
      PERSISTENCE_MEMTABLES_FLUSH_IDLE_AFTER_SECONDS: 2
  contextionary_service:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
      - "9999:9999"
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080